project:
  type: website
  render:
    - index.qmd
    - posts

website:
  title: "ASJ analytics and software"
  site-url: https://theasjblog.github.io/analytics/
  description: "Analytics, software, and everything in between"
  favicon: img/logo.png
  cookie-consent: false
  google-analytics: "TODO"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
    right:
      - icon: github
        href: https://github.com/theasjblog
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/adrian-joseph/
        target: _blank

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      text: |
        <link rel="apple-touch-icon" href="https://theasjblog.github.io/analytics/img/logo.png">
