---
title: "Shiny dynamic create stuff"
description: "Subtitle"
---

### Shiny dynamic create stuff

Subtitle

### What will you learn?

In this tutorial, you will learn how to create UI elements when you cannot anticipate how many of them you need.

### Why is it important?

This techniques expand the flexibility of your Shiny apps by removing the need to create all UI elements when the app starts.

### When does it apply?

In some cases you might to build reactive elements based on some user choices that you cannot anticipate. We will consider a simple example here, but there are countless of other cases when this will be applicable.

### Today's example

To keep things simple, we want to create a Shiny apps that allows a user to select how many text inputs he wants to use. There will then be a table displaying all the inputs provided. Here is the sketch:

The challenge with this application is that we cannot know before hand how many inputs the user will need, so we cannot create the UI reactive elements when the app starts.

#### The basic idea

The main idea is to create the UI elements inside the generic container `uiOutput`. Within this container, the dynamic UI elements are generated with a loop. We will be using an `lapply`, but a `for` loop will work as well.

INSERT SNIPPET

Note how the ui elements have an ID generated from the loop index. This is important because it later allows us to access the content of the input using the known name pattern. Do not name your inputs randomly.

This simple trick gets half way there. If your dynamic UI element is an output, i.e., a chart, a table, or a `textOutput`, then you are done.

But what if you want to use your dynamic UI element as inputs? You need to have a way to monitor them. There are a few ways to do this, but thay all revolve around the principle of looping through the dynamic UI elements, either directly or within an `observeEvent`. Today we will look at the implementation that does not use `observeEvent`.

INSERT SNIPPET

We know the number of dynamic UI elements we have because of the value of `input$numberOfInputs`. We then loop through all our dynamic UI elements, we collect their values and add them to the table.

And there is it, all done. We can now create Shiny apps that allows for an arbitrary number of UI elements.

As a word of caution, if you use this technique make sure you validate the number of UI elements that are going to be created. In our demo app this happens implicitly bacause we use a slidebar selectors. The last thing you wna tis for your app to attempt to create thousands of UI elements.

### Are there other options?

There are ways to implement this technique, and you might find them in stackoverflow or similar websites. There is nothing wrong with (some) of those approach: they are based around the same idea presented here. I have seen some options based on injecting JS into the Shiny generated code. I would suggest you avoid that unless absolutely necessary. Try to keep your solution simple and all in one language if you want to avoid maintenance nightmares.

An even better approach is to think about your app design. Is there any way you can avoid having to do this in the first place? The approach presented here works and is reasonably simple, but if you can avoid having to do relay on this kind of mechanisms in the first place this would be ideal.

### Conclusion

COPY-PASTE the final call to action
